clone:
  recursive: true
  submodule_update_remote: true


script:
  build:
    image: sivel/allsnakes
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - netstat -pntl
      - ls -al /sys/fs/cgroup
      - ./test/utils/run_tests.sh


services:
  dind:
    image: docker:dind
    privileged: true


volumes:
    "/sys/fs/cgroup:/sys/fs/cgroup:ro":


matrix:
  include:
    - TARGET: sanity
      TOXENV: py24
    - TARGET: sanity
      TOXENV: py26
    - TARGET: sanity
      TOXENV: py27
    - TARGET: sanity
      TOXENV: py34
    - TARGET: sanity
      TOXENV: py35
    - TARGET: centos6
    - TARGET: centos7
      TARGET_OPTIONS: "--volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - TARGET: fedora23
      TARGET_OPTIONS: "--volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - TARGET: fedora-rawhide
      TARGET_OPTIONS: "--volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - TARGET: ubuntu1204
    - TARGET: ubuntu1404
