clone:
  recursive: true
  submodule_update_remote: true


script:
  build:
    image: sivel/allsnakes
    commands:
      - apt-get update
      - apt-get install -y apt-transport-https ca-certificates
      - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
      - echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' > /etc/apt/sources.list.d/docker.list
      - apt-get update
      - apt-get install -y docker-engine libffi-dev
      - netstat -pntl
      - ./test/utils/run_tests.sh


services:
  dind:
    image: docker:dind
    privileged: true


matrix:
  include:
    - TARGET: sanity
      TOXENV: py24
    - TARGET: sanity
      TOXENV: py26
    - TARGET: sanity
      TOXENV: py27
    - TARGET: sanity
      TOXENV: py34
    - TARGET: sanity
      TOXENV: py35
    - TARGET: centos6
    - TARGET: centos7
      TARGET_OPTIONS: "--volume: /sys/fs/cgroup:/sys/fs/cgroup:ro"
    - TARGET: fedora23
      TARGET_OPTIONS: "--volume: /sys/fs/cgroup:/sys/fs/cgroup:ro"
    - TARGET: fedora-rawhide
      TARGET_OPTIONS: "--volume: /sys/fs/cgroup:/sys/fs/cgroup:ro"
    - TARGET: ubuntu1204
    - TARGET: ubuntu1404

