clone:
  recursive: true
  submodule_update_remote: true


script:
  build:
    image: ${TARGET}
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
#      - "/var/run/docker.sock:/var/run/docker.sock"
#    environment:
#      - DOCKER_HOST=unix:///var/run/docker.sock
    commands:
      - netstat -pntl
      - ls -al /sys/fs/cgroup
      - ./test/utils/run_tests.sh


#services:
#  dind:
#    image: docker:dind
#    privileged: true


matrix:
  include:
    - TARGET: sivel/allsnakes
      TOXENV: py24
    - TARGET: sivel/allsnakes
      TOXENV: py26
    - TARGET: sivel/allsnakes
      TOXENV: py27
    - TARGET: sivel/allsnakes
      TOXENV: py34
    - TARGET: sivel/allsnakes
      TOXENV: py35
    - TARGET: "ansible/ansible:centos6"
    - TARGET: "ansible/ansible:centos7"
    - TARGET: "ansible/ansible:fedora23"
    - TARGET: "ansible/ansible:fedora-rawhide"
    - TARGET: "ansible/ansible:ubuntu1204"
    - TARGET: "ansible/ansible:ubuntu1404"
