build:
  image: sivel/allsnakes
  commands:
    - apt-get update
    - apt-get install apt-transport-https ca-certificates
    - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    - echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' > /etc/apt/sources.list.d/docker.list
    - apt-get update
    - apt-get install docker-engine
    - git submodule update --init --recursive
    - ./test/utils/run_tests.sh


compose:
  dind:
    image: docker:dind
    privileged: true


matrix:
  ENVSTRING:
    - TARGET=sanity TOXENV=py24
    - TARGET=sanity TOXENV=py26
    - TARGET=sanity TOXENV=py27
    - TARGET=sanity TOXENV=py34
    - TARGET=sanity TOXENV=py35
    - TARGET=centos6
    - TARGET=centos7
    - TARGET=fedora23
    - TARGET=fedora-rawhide
    - TARGET=ubuntu1204
    - TARGET=ubuntu1404
